version: "3.1"
services:
  nuxt:
    build: .
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db