version: "3.1"
services:
#  nuxt:
#    image: node:latest
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./src:/app
#    working_dir: /app
#    command: "npm run build && npm start"
#    depends_on:
#      - db

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db