version: "3.1"
services:
  nuxt:
    image: node:21.6.1
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db